dfe-analytical-services/analysts-guide

- README.md
- _quarto.yml
- index.qmd
- statistics-production/ees.qmd
- statistics-production/pub.qmd
- statistics-production/scrums.qmd
- writing-visualising/visualising.qmd
- writing-visualising/writing.qmd
Breaking out the writing and visualising page across the EES page, and 3 new pages:
1. Writing about data
2. Visualising data
3. Publication scrums
I've also added a link to the RAP for stats guidance in the statistics production section so that points to the RAP for stats page from the RAP section given that people may look for it in either place.
One final thing is that I've also 'corrected' (hopefully!) the title to be `Analysts' Guide` - happy to be corrected on this if I've got it wrong!
It looks like a lot of changes but most of it was copy / paste, with some deletions of unnecessary / duplicating sections along the way. There's a few bits of original content, though these are mainly at the top of the 3 new pages and in certain sections to help them read easier to new readers.
As …
> Writing and Visualising separation

- RAP/rap-statistics.qmd
- writing-visualising/dashboards.qmd
Added some updates to the stats production peer review guidance based on info from the [Duck Book](https://best-practice-and-impact.github.io/qa-of-code-guidance/peer_review.html)
Also changed all the mentions of the SDT mailbox on the dashboard page to be mailto links.
> Updates to peer review guidance

- learning-development/git.qmd
- renv.lock
Update the outdated link. 
Old link is broken/gives 404 error
> update the link to the DfE DevOps reference guide site

- learning-development/sql.qmd
Add a link to GitLab's SQL style guide, as well as update the accessing SSMS section to have a service desk link.
Style guide looks useful, and we don't currently link to one for SQL. It aligns with the notes we already have on the page but gives extra detail as well.
SSMS now requires a service desk request for it to appear in your software centre to download, noticed our notes on it were out of date so updated to add the link for the request.
Not applicable.
No related issues.
> Add sql style guide

- learning-development/r.qmd
We noticed in the workshop these are broken. I think this is because RStudio is now POSIT and they've moved where they store the cheatsheets about a bit and made some as full html pages.
> Update cheatsheet links

- learning-development/sql.qmd
Fixed 2 broken links in the SQL section: [https://dfe-analytical-services.github.io/analysts-guide/learning-development/sql.html#how-to-work-with-sql](https://dfe-analytical-services.github.io/analysts-guide/learning-development/sql.html#how-to-work-with-sql)
The first link was an easy replacement but I'm not sure about the 2nd link as the wording seems to have changed? The original link was [https://dfe-analytical-services.github.io/analysts-guide/RAP/rap.html#Single_publication_production_script](https://dfe-analytical-services.github.io/analysts-guide/RAP/rap.html#Single_publication_production_script) and I swapped it for [https://dfe-analytical-services.github.io/analysts-guide/RAP/rap-statistics.html#whole-publication-production-scripts](https://dfe-analytical-services.github.io/analy …
> fixing 2 broken links

- learning-development/git.qmd
Add guidance on how to write good commit messages when using Git.
It's a question we regularly get from new starters, plus I wanted a place to stash a link to the Git commit convention site too for future reference.
1. Have moved the commits section above the branches section under 'Tips for using Git' as it felt like a more logical starting place (though up for debate!)
2. Added generic advice on committing regularly (another frequent question we get)
3. Moved the existing commit guidance into a specific 'In RStudio section'
4. Added details on how to write good commit messages and a link to the commit conventions site
Screenshot of a local build showing the formatting of the new guidance:
N/A - though there is a [Trello card on our SDT board that …
> Add git commit message guidance

- statistics-production/ud.qmd
We need some additional guidance on the protocol for giving both filter and indicator fields a name. This PR adds this into the Open Data Standards page.
We need consistency across the data catalogue in terms of how fields are named to:
- help make it easier for users to navigate data
- optimise how we store data and associated meta-data
- provide standardised data for API users.
> Field naming conventions

- learning-development/r.qmd
Update analytics academy link and add note on access/trello accounts. 
Old access link had expired, and it was unclear that you need a trello account and to request access the first time.
> Update analytics academy link and add note on access

- _quarto.yml
Temporarily changed dark theme from [https://bootswatch.com/slate/](https://bootswatch.com/slate/) to [https://bootswatch.com/cyborg/](https://bootswatch.com/cyborg/) until we can get a fix in for the old dark theme
> updating dark theme because the other one broke

- ADA/git_databricks.qmd
Images on [https://dfe-analytical-services.github.io/analysts-guide/ADA/git_databricks.html](https://dfe-analytical-services.github.io/analysts-guide/ADA/git_databricks.html) were broken as all of the .png file endings were in caps. They should all be working now!
> fixing broken image links

- renv.lock
- renv/activate.R
- statistics-production/ud.qmd
I've created a set of standardised special educational needs filter entries based on the School Census guidance (which is where most stats producers source their SEN data) and review by the data harmonisation champions group.
We want to create consistent standards across DfE data sets.
I've added details of the standardised SEN filters in the Open data standards page alongside ethnicity and sex.
> Added standardised SEN fields

- statistics-production/ud.qmd
Similar to the SEN data guidance update, this presents the first iteration of standardisation of the school type fields as reviewed by the data harmonisation champions.
These are part of the ongoing effort to establish standardised data guidance for publication teams to follow.
Standard field names and items are outlined for:
Establishment type group
Establishment governance
Education phase
Establishment type
Provider type
> Added establishment types reference data

- statistics-production/ud.qmd
Quick change to example code for writing CSVs in UTF-8 encoding.
I tried to use the guidance and noticed the argument is different now.
We previously advised using `encoding = XX`, but apparently this is now `fileEncoding =  XX`
None
> write.csv() update

- learning-development/r.qmd
I've added some additional detail about making sure that users have Chrome installed to avoid the chromote error, plus moved some of the subsections under a troubleshooting header to make them easier to find (you can get rid of that if you hate it)
> updating chromote section and adding troubleshooting header

- learning-development/r.qmd
I've added a paragraph on what analysts should do if they're blocked by an SSL cert type error.
> Added guidance on SSL cert errors

- learning-development/learning-support.qmd
- learning-development/r.qmd
Real quick update to analytics academy link which is now hosted on SharePoint rather than trello
> update analytics academy link to point to new SharePoint area

- _quarto.yml
- index.qmd
- learning-development/accessibility.qmd
- learning-development/sql.qmd
- renv.lock
Add a new accessibility tools and guidance page in the learning resources section
Request by an analyst for a list of free tools to get started with, expanded into making this page so it's available for everyone and we can build it up over time too.
1. New accessibility resources page
2. Updated renv snapshot to latest R version
3. Fix broken link to RAP pages from SQL page
Fixes #54
> Add accessibility resources page

- statistics-production/ees.qmd
- statistics-production/embedded-charts.qmd
- statistics-production/scrums.qmd
- statistics-production/ud.qmd
- writing-visualising/dashboards.qmd
- writing-visualising/dashboards_rshiny.qmd
Swap the mailboxes from SDT to EES
The team has split so we're now splitting the responsibilities for each mailbox more clearly
Changed a bunch of EES and dashboard pages, left the overall references as Jen / SDT are the overall owner, and also the references in learning resources and RAP sections as they sit with SDT
Places where references to SDT mailbox still exist:
Resolves #65
> swap sdt for ees mailbox on ees / dashboards pages

- statistics-production/ud.qmd
Adding numberstring as an acceptable indicator_unit.
We'd added it into EES this week, so the guidance should match to tell users it's an option.
Added a new table that lists all acceptable values in it with a quick description of what they do.
Weirdly, I think the missing TOC issue might be fixed as a result of these changes now too? @rmbielby @jen-machin 
None
> Add numberstring and more detailed indicator unit notes

- ADA/ada.qmd
- ADA/databricks_fundamentals.qmd
- ADA/databricks_notebooks.qmd
- ADA/databricks_rstudio_personal_cluster.qmd
- ADA/databricks_rstudio_sql_warehouse.qmd
- ADA/databricks_workflow_script_databricks.qmd
- ADA/databricks_workflow_script_rstudio.qmd
- ADA/databricks_workflows.qmd
- ADA/git_databricks.qmd
- _quarto.yml
- theme-dark.scss
- theme-light.scss
ADA / Databricks section has been split into 2, one containing information about Databricks and how it works, and one containing how to guides if users just want to be able to follow steps to get something set up
If users need to get things up and running to work with Databricks, it might be offputting if they have to navigate a long page of information first. Alternatively, users might just want to read some background info about Databricks before agreeing to begin migration and might not want to get into technical specifics / details. 
Navigation menu for Databricks split into 2 sections
Minor tidy up of line breaks / typos / page titles
**Note:** Although some of the Databricks pages have been merged into main, they're not available on the live guidance site because they weren't …
> Splitting Databricks section in 2 

- writing-visualising/dashboards_rshiny.qmd
The guidance on deploying Shiny apps to the internal Posit Connect platform has been updated and moved home, so I've updated the links to reflect this.
Users need to be able to find guidance on deploying apps.
I've updated the link to point to the new guidance page and also updated the service now links now that those have switched to ithelpdesk instead of service portal.
> Updated links to internal Posit Connect deployment guidance

- index.qmd
Somehow the EES analytics URL on the homepage has changed, used to be:
https://dfe-analytical-services.github.io/analysts-guide/statistics-production/user_analytics.html (currently gives a 404)
is now:
https://dfe-analytical-services.github.io/analysts-guide/statistics-production/user-analytics.html
> fix to broken EES analytics link on homepage

- ADA/ada.qmd
Adding ADA jargon buster link
Linking to the 'ADA jargon buster' from the analyst guide so it's easy to find and people realise it exists. 
Adding to the ADA and Databricks section of Analysts Guide. Have suggested we add relatively near the top as a callout-tip box to make it easy for readers to spot. There is a section further down which gives links to ADA support - one of these already links to the page where you can also find the jargon buster, so haven't suggested we add here. 
Add a link to the ADA 'jargon buster' #113
> Adding ADA jargon buster

- .github/workflows/publish.yml
- renv.lock
- statistics-production/ud.qmd
Basically just re-run renv::snapshot(). Some of the packages seem to have dropped off the renv.lock listing in one of the recent PRs, so the build was failing when it came to functions from those (readxl was the first one it was hitting and stopping it in it's tracks). 
Also realised when I created the PR that there's no test build of the site, which has partially contributed to the current issues, so I've added a test build into the workflow. It automatically triggers off any PR going into the main branch and it's run successfully on this one so we can see it's working. Note it's also successfully *not* published it to GitHub pages, it's only done a test build and then stopped short of publishing it.
> Updating renv snapshot with non-recorded packages (e.g. readxl)

- writing-visualising/dashboards_rshiny.qmd
Changed the "creating R shiny dashboards" page to have a couple of callouts to draw attention to when people should be contacting the EESP team
Several people contacting us last minute for help with required changes
> adding callouts to better highlight required dashboard timelines

- learning-development/accessibility.qmd
Made some quick changes to update the order of the page, and tidy up some of the headings in the checking accessibility for spreadsheets section.
These have cleaned the page up / make it easier for me to navigate, though interested to know if the same goes for anyone else.
Was linking someone else to the page and found the main bits I wanted to reference were now split, so felt it would be cleaner if the spreadsheet accessibility section was one big section and at the bottom.
Not needed
No related issue
> Reorder accessibility page

- learning-development/learning-support.qmd
Adding the link to DevOps guidance right at the top of the page in a call-out box. Suggested tidying up the page a little by adding an extra header and moving the email links from the top section to be with the SDT email address below. 
So users can navigate the page a little easier and know what to find in each section, plus make it much easier for users to find the DevOps guidance
Added the DevOps link in a callout at the top of the page. This was originally done for us by an external user as per this PR: 
https://github.com/dfe-analytical-services/analysts-guide/pull/102. We were unable to approve this as it was forked. 
I have then also attempted to tidy up the page a little by adding an extra heading and moving the email address support to be together. I have then removed the bullets …
> 99 tidy up git learning resources page

- .gitignore
- learning-development/r.qmd
- writing-visualising/dashboards_rshiny.qmd
Recent new error on shinytest2 since Chrome and Edge removed support for the old headless mode.
So people can still use shinytest2
- Updated R-Shiny dashboard page to more succinctly send people through to the R support materials
- Added an overview and solution to the headless mode error in the R support materials
> Added guidance on dealing with chromote headless mode

- .github/workflows/prs-to-trello.yml
- statistics-production/ud.qmd
Some additions to the data standards to help them work with team's data.
Working with a team handling SEN data and covering off some mild pain points. In some places Total isn't appropriate as the top level aggregation, plus the option of defining custom default categories in EES is coming through soon, so things like All pupils, All White can be defined as the default category going for and teams can move away from Total for more things.
I've added the following:
- Standard top level aggregations for sen_provision and sen_status (All pupils, All SEN provision etc)
- Standard top level ethnicity minor aggregations as alternatives to just using Total (i.e. All White, etc)
- phase_type_grouping, we looked at moving away from this, but team's find it challenging as it sounds like it's …
> Data standards - updating SEN and school type standards

- ADA/databricks_rstudio_personal_cluster.qmd
- ADA/databricks_rstudio_personal_cluster_sparklyr.qmd
On Databricks personal cluster pages <> were being used around values to be entered into .Renviron file, but on SQL warehouse page "" were being used. The angle brackets were confusing to some people so I have replaced them with "" for consistency.
> removed angle brackets and replaced with "" for consistency

- ADA/databricks_rstudio_personal_cluster.qmd
- ADA/databricks_rstudio_personal_cluster_sparklyr.qmd
- ADA/databricks_rstudio_sql_warehouse.qmd
- RAP/rap-statistics.qmd
- Nick requested that we add a callout to the Databricks Host sections to remind people not to include the / as it breaks things and he's seen quite a few people run into that issue
- There was a broken README link on the RAP page, I've removed it because the README is now embedded in code rather than being a standalone .md file that we can link to
> Adding callout to Databricks host info and removing broken README link

- ADA/databricks_rstudio_personal_cluster.qmd
Updated guidance on how to find Databricks Cluster Path for .Renviron file to allow users to connect personal cluster to RStudio 
Current instructions are wrong
Should address issue #157
> Fixing personal cluster instructions

- learning-development/r.qmd
issue #76 - add the helpful link to https://r-graph-gallery.com/ to the R learning resources page
To signpost to a useful external resource :)
Just one additional bullet point added to the existing 'other resources' list.
#76
> add gallery of R charts link to 'other resources' section in R

- index.qmd
Link to using Databricks with Git page on Analysts Guide homepage was broken
Should resolve issue #166
> Fixing broken Databricks link 

- ADA/databricks_rstudio_personal_cluster_sparklyr.qmd
A user raised the following issue when trying to connect to Databricks from RStudio using a personal cluster on Azure Virtual Desktop: 
All the connection setup steps in the guidance worked, but when trying to run the spark_connect() function, the code just runs and runs for a long time and doesn't return anything at all.
Upon investigation, it was because they were missing a config.yml file. Adding a blank one fixes the problem. I've added this to the troubleshooting section on the Personal cluster with RStudio and `sparklyr` page
To help other uses who encounter the same issue
> Added info on missing config file when using Databricks on AVD

- statistics-production/ud.qmd
I spotted an inconsistency in one of the lines of the variable naming framework, so just quickly fixing it to bring it in line with the rest of the text.
Error in the guidance.
Data type was listed in the wrong place in one line of the variable naming framework. I'm just bringing it back in line with the rest of the text / guidance.
> Update variable naming conventions in ud.qmd

- learning-development/r.qmd
Update link in renv section of r.qmd script to point to correct location
Previous link was broken
Update rap.html to rap-start-guide.html
#174 
- [✅] I have checked the contributing guidelines
- [✅] I have checked for and linked any relevant issues that this may resolve
- [✅] I have checked that these changes build locally
- [✅] I understand that if merged into main, these changes will be publicly available
> fix 'recyclable code for future use' link in r.qmd

- learning-development/sql.qmd
Updating broken link 
The current link takes you to a 404 page not found error. This may be frustrating to users, who then may give up looking for the link and not find information on SQL best practice 
Updating the SQL style guide link to the new and working link 
#165
> Updating broken link to SQL style guide

- learning-development/git.qmd
- learning-development/sql.qmd
Amending links to SQL introduction and intermediate videos and editing broken link to Git Academy
The previous links were broken, with the error message 'this video cannot be loaded'. Git Academy link was pasted twice so was not working. 
Amending the SQL links to the updated version. The link now requests that internal users log in before being able to view the video.  Removing the duplication on the Git Academy link so it works.
> Fixing SQL video links

- learning-development/r.qmd
Quick troubleshooting note for issues when using `renv::restore()`.
I was having some pain restoring a new clone of the shiny-template repo on a branch and then found that I could just `renv::init()` to reset all packages to their latest version (which is usually the fix I do in this instances).
Added a note on the `renv::init()` option, but also notes on how to deal with individual difficult packages.
No related issue.
> Add renv troubleshooting tip

- statistics-production/embedded-charts.qmd
- Correct the relative paths and anchor names for all four links under **Development requirements** in statistics-production/embedded-charts.qmd
- The existing links (dashboards.html#accessibility-testing, etc) point to the wrong folder and use anchors that don’t exist, resulting in 404 errors when the site is published
- **File**: statistics-production/embedded-charts.qmd
- **Before**:
```markdown
* [Accessibility](dashboards.html#accessibility-testing);
* [Reliability](dashboards.html#testing-r-shiny);
* [Performance](dashboards.html#performance-testing);
* [Coherent styling](dashboards.html#styling).
```
- **After**:
```markdown
* [Accessibility](../writing-visualising/dashboards.html#accessibility);
* [Reliability](../writing-visualising/dashboards.html#code-testing);
* …
```
> issue #199 Updating broken links

- statistics-production/ud.qmd
Belated following up on this PR from the data screener (and work done on EES even longer ago): https://github.com/dfe-analytical-services/dfe-published-data-qa/pull/154
New functionality in EES>
EES now accepts alternative definitions for default filter items.
> Added filter_default to underlying data guidance

- _quarto.yml
- index.qmd
- learning-development/datacamp-tracks.qmd
Adding in the new Datacamp tracks content, designed to support Analysts' development. The page sets out 6 different tracks - by experience and skill level, plus an AI for all track. 
This page means the tracks content developed by Sean is more easily accessible to all analysts in DfE. This should save analysts time by directing to the right Datacamp courses for them, as well as giving them direction in where to go after their current course or track is complete. 
- Added the Datacamp tracks page as designed by Sean 
- Added the page to quarto,yml 
- Added a link to the front page by adding to the index.yml
> New page - Datacamp tracks
