statistics-production/pub.qmd

Neatening the checklist page (removing content that is no longer relevant as it was legacy guidance from when EES had just started and updating links).
- [x ] I have checked the contributing guidelines

Checklist page additions

---

statistics-production/examples.qmd
writing-visualising/visualising.qmd
writing-visualising/writing.qmd

Mostly updating the links to the right places for our guidance on each of the sections. Also added a section for 'Active subheadings' as there was a good example of it, but we didn't have any guidance talking about active subheadings in particular.

Example page additions

---

README.md

Add a quick history of old versions and their repos to the readme.
Ease of reference moving forwards.

add past versions of site into readme

---

statistics-production/user-eng.qmd

Cutting down some of the content on this page, and adding subheadings/neatening links to make the page easier to navigate.

Engagement page additions

---

learning-development/learning-support.qmd
statistics-production/embedded-charts.qmd

Stole list of workshop contents from previous email invites and added them to the learning support page 😆

added more info on R/Git workshops to learning support page

---

statistics-production/ud.qmd

Just added a line to the table with the LSIP definition
FE publication team asked for LSIPs as a geographic level

Added LSIPs to geographic level table

---

learning-development/r.qmd

Created a new using R to connect to SQL section and moved the existing running SQL queries in R section into it. Added a short intro section on dplyr and then added the error and associated fix for the DBI varchar(max) bug.
The SQL in R section was a bit light on some useful topics now that more people are using R in this way. The DBI bug is quite a common one so needed referencing, but also didn't look like we'd really given much attention to dbplyr in the existing guidance.

Added R/SQL DBI varchar(max) error solution

---

ADA/databricks_rstudio.qmd

Add video and link to new repo on pulling data from Databricks into R studio

add link to ADA_Rstudio_connect GitHub repo

---

learning-development/r.qmd

Added some text on fixing the Chrome/shinytest2 issue using the .Renviron file.

Added guidance on shinytest2 chrome fix

---

RAP/rap-statistics.qmd

Crudely wedging in a link to the tidy team code review guidance.
I saw it and wanted to keep the link stashed somewhere.
N / A
N / A

add link to tidyteam code review guidance

---

RAP/rap-faq.qmd
RAP/rap-statistics.qmd
learning-development/git.qmd
learning-development/r.qmd
learning-development/sql.qmd

Found quite a few broken links to the RAP pages but I think I've fixed them!!

Broken capability link

---

_quarto.yml

Quick change to update the footer year.
Footer said 2023 but we're now in 2024.
Not needed. Haven't built locally as shouldn't need it
No related tickets.

Update footer year to 2024

---

ADA/ada.qmd

Fixing broken Databricks link on ADA page

fixing broken databricks link

---

writing-visualising/dashboards_rshiny.qmd

Fixing a broken link spotted by one of our analysts
Previous link was broken, and guidance was out of date, we now use the afcolours package for colours.
Pretty straightforward.
No related issues
I have edited this directly in GitHub as I'm confident the markdown is straightforward enough not to need testing locally - though we should double check once merged it's actually worked...

Fix broken style sheet link

---

renv.lock
statistics-production/ud.qmd

Playing with things to see if we can get all of the TOC for the open data standards page to appear on the live site.
Shot in the dark to see if I could fix it while I had it open.
Updated package versions, removed the jumbotron above it, and played with the spacing around the header where it seems to break a bit.
Threw some goats into a volcano and prayed to the god almighty.
We won't know if it's worked until it's merged.
None

Sacrifice the goats to see if I can make the TOC work

---

statistics-production/ud.qmd

More goats into a volcano to make the TOC work on the Open Data Standards page
Want to fix a thing and throwing things at it
Won't know if it's fixed until merged
None

fix the headings and blank row in table, more goats in a volcano

---

ADA/databricks_fundamentals.qmd

Found a broken link and fixed it
The link was broken

fixing a broken link to the notebooks page

---

index.qmd
statistics-production/ees.qmd
statistics-production/embedded-charts.qmd
statistics-production/pub.qmd
statistics-production/ud.qmd
writing-visualising/dashboards.qmd

Addressing outstanding issues referenced in #98 and #69.
General tidy up of the page, updating mailboxes after team split, removing h1s.
On the data page, added a bit more detail around CSVs and standardised the way we reference them to meet style guides.
Can be found in #98.
Resolves #98. Resolves #69.

EES page tidy up

---

ADA/ada.qmd
ADA/databricks_fundamentals.qmd
ADA/databricks_notebooks.qmd
ADA/databricks_rstudio_personal_cluster.qmd
ADA/databricks_rstudio_personal_cluster_sparklyr.qmd
ADA/databricks_rstudio_sql_warehouse.qmd
ADA/databricks_workflow_script_databricks.qmd
ADA/databricks_workflow_script_rstudio.qmd
ADA/databricks_workflows.qmd
ADA/git_databricks.qmd
_quarto.yml
styles.css
theme-dark.scss
theme-light.scss

Whoops this one spiralled a little bit
- Fixing some broken links on the SQL warehouse page (reported by a user)
- Adding an announcement that appears at the top of the page to remind people that the Databricks interface can change and they should let us know if our guidance doesn't match what they see on the platform (Requested by Laura)
- Adding custom colours for scrollbars in light and dark themes
- Some minor modifications to sidebar / body widths to give us a bit more space for the menu since we recently added MORE new Databricks pages. I've tested this on a Surface Pro-sized screen and on my bigger monitor, but would be useful to know if it causes havoc for other people. 
- Moving Databricks fundamentals pages into "learning support" section as they seemed more at home there, which …

Fixing broken links and making small layout modifications

---

.github/workflows/prs-to-trello.yml
statistics-production/ud.qmd

Microsoft Stream has been deprecated, so there were errors showing in place of videos. I can't seem to retrieve these videos so have removed reference to them entirely for now. 
**Update:** Rich has found the videos, so can put them somewhere sensible and add links to them.  
#149

Broken image links on Open Data page

---

index.qmd

Moving some Databricks links on welcome page to the right place, and adding in a few missing ones

Homepage was out of date and missing links

---

ADA/databricks_rstudio_personal_cluster.qmd
ADA/databricks_rstudio_personal_cluster_sparklyr.qmd

Updated the method to connect to Databricks through RStudio using sparklyr.
pysparklyr and sparklyr have been updated and the method of connecting in the guidance no longer works.
Added details on how to install the databricks_connect functionality to allow RStudio to interface with Databricks

Sparklyr method update

---

statistics-production/ees.qmd

Adding some specific guidance on naming publications.
We didn't have guidance (shocking!) so needed to get this written down so it's not just in my head.
Guidance on rules, restrictions and things to think about when titling publications. Update to summary section too as the two are closely tied together.
Not fully happy with it as it feels wordy but happy for the review to attack / refine / challenge that.
Resolves #185

Add publication title guidance

---

ADA/databricks_rstudio_personal_cluster_sparklyr_archive.qmd
_quarto.yml
index.qmd

Archiving sparklyr page and added a page with a message explaining why to stop too many questions to the mailboxes.
sparklyr is not stable enough right now and the guidance keeps changing.
- added archive qmd and linked the page (in the side menu/toc) to it
- removed the link from the index (home) page

Archive sparklyr
